/*------------------------------------------------------------------------------
 * Name       : FundsOfMandatesData.cs
 * Created By : Dhanej 
 * Created On : 28 Sep 2020
 * Updated On : 28 Sep 2020
 * Purpose    : Class file to handle collection of FundOfMandates
 * Comments   :
 * Note       : This source code was auto-generated by xsd, Version=4.8.3928.0.
-----------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;

namespace Rabobank.Training.ClassLibrary.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class FundsOfMandatesData
    {

        private FundOfMandates[] fundsOfMandatesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FundOfMandates", IsNullable = false)]
        public FundOfMandates[] FundsOfMandates
        {
            get
            {
                return this.fundsOfMandatesField;
            }
            set
            {
                this.fundsOfMandatesField = value;
            }
        }
    }
}
