/*------------------------------------------------------------------------------
 * Name       : FundsOfMandates.cs
 * Created By : Dhanej
 * Created On : 28 Sep 2020
 * Updated On : 28 Sep 2020
 * Purpose    : Class file to handle FundsOfMandates Objects
 * Comments   :
 * Note       : This source code was auto-generated by xsd, Version=4.8.3928.0.
-----------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;

namespace Rabobank.Training.ClassLibrary.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class FundsOfMandates
    {

        private FundOfMandates[] fundOfMandatesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FundOfMandates")]
        public FundOfMandates[] FundOfMandates
        {
            get
            {
                return this.fundOfMandatesField;
            }
            set
            {
                this.fundOfMandatesField = value;
            }
        }
    }
}
