/*------------------------------------------------------------------------------
 * Name       : Mandates.cs
 * Created By : Dhanej
 * Created On : 28 Sep 2020
 * Updated On : 28 Sep 2020
 * Purpose    : Class file to handle collection of Mandate
 * Comments   :
 * Note       : This source code was auto-generated by xsd, Version=4.8.3928.0.
-----------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;


namespace Rabobank.Training.ClassLibrary.Models
{ 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute( IsNullable = false)]
    public partial class Mandates
    {

        private Mandate[] mandateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mandate")]
        public Mandate[] Mandate
        {
            get
            {
                return this.mandateField;
            }
            set
            {
                this.mandateField = value;
            }
        }
    }
}
