/*------------------------------------------------------------------------------
 * Name       : Mandate.cs
 * Created By : Dhanej
 * Created On : 28 Sep 2020
 * Updated On : 28 Sep 2020
 * Purpose    : Class file to handle Mandate Objects
 * Comments   :
 * Note       : This source code was auto-generated by xsd, Version=4.8.3928.0.
-----------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;

namespace Rabobank.Training.ClassLibrary.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class Mandate
    {

        private string mandateIdField;

        private string mandateNameField;

        private decimal allocationField;

        /// <remarks/>
        public string MandateId
        {
            get
            {
                return this.mandateIdField;
            }
            set
            {
                this.mandateIdField = value;
            }
        }

        /// <remarks/>
        public string MandateName
        {
            get
            {
                return this.mandateNameField;
            }
            set
            {
                this.mandateNameField = value;
            }
        }

        /// <remarks/>
        public decimal Allocation
        {
            get
            {
                return this.allocationField;
            }
            set
            {
                this.allocationField = value;
            }
        }
    }
}
